void main(){
  // Exception Handling

  try{

  }catch(error){

  }

  // Fault tolerant application

}